Fix compilation warning due to vhost-scsi migration code mismerge
The vhost-scsi migration patches were mismerged (into 2.9.0) resulting in the following compilation
warning:

/hw/scsi/vhost-scsi.c:231:5: error: initialization from incompatible pointer type [-Werror]
     .pre_save = vhost_scsi_pre_save,
     ^
/hw/scsi/vhost-scsi.c:231:5: error: (near initialization for 'vmstate_virtio_vhost_scsi.pre_save') [-Werror]

This is due to an upstream change in the 'pre_save' routines (post 2.9.0) to return 'int' instead of
'void'. As such, modify vhost_scsi_pre_save() to return 'void'.

Fixes: d18def57fa5d ("vhost-scsi: Add VMState descriptor")

Orabug: 30185587

Reported-by: Maran Wilson <maran.wilson@oracle.com>
Reviewed-by: Liran Alon <liran.alon@oracle.com>
Signed-off-by: Mark Kanda <mark.kanda@oracle.com>